[package]
name = "distributed-cache-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }   # асинхронный ввод-вывод + планировщик
dashmap = "6"                        # конкурентная хэш-таблица
nom = "8"                                         # парсер протокола RESP2
serde_json = "1.0"                              # работа с JSON
anyhow = "1"                                    # удобные обёртки ошибок (или thiserror)



